version: '3.9'

services:

 php:
  container_name: php
  build:
    args:
      user: advant
      uid: 1000
    context: .
    dockerfile: ./php/Dockerfile
  ports: [ '9000:9000' ]
  volumes:
    - ./app:/var/www
#      condition: service_healthy

 nginx:
  container_name: nginx
  image: nginx:stable-alpine
  ports: [ '80:80' ]
  volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - php

 mysql:
  container_name: mysql
  env_file:
   - './app/.env'
  image: 'mysql:8.0' 
  ports: [ '3306:3306' ]
  volumes: 
    - mysql_data:/var/lib/mysql
#    - ./mysql/emailsender.sql:/docker-entrypoint-initdb.d/emailsender.sql:ro
#  healthcheck:
#      test:  mysql --user=emailsender --password=emailsender -e 'SHOW TABLES FROM emailsender'
#      timeout: 20s
#      retries: 10

 myadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports: [ '8080:80' ]
  environment:
   - PMA_ARBITRARY=1
   - PMA_HOST=mysql
  depends_on:
   - mysql

volumes:
 mysql_data:
